spring.application.name=auth-service 
spring.profiles.active=${ACTIVE_PROFILE:dev}
server.port=8085

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# # MySQL database 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT 
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:139101420fb14f0d6568b8423701055bb8a3973440e0746e65f325d4d6debdc6}

# 1h in millisecond
security.jwt.expiration-time=3600000