# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# MySQL database connection
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/jwt_auth?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:}
